[build]
  command = "git lfs install && git lfs pull && npm run build"
  publish = ".next"

[build.environment]
  GIT_LFS_ENABLED = "true"
  GIT_LFS_FETCH_INCLUDE = "public/images/blanks/**"

[[plugins]]
  package = "@netlify/plugin-nextjs"
